### ISSUE TITLE
Not an issue but a question/request

### ISSUE THREAD

**Issue by fleps** [yenyang/Anarchy-BepInEx#1]
Hey man, great mod.

Could you maybe look into making Bulldoze somehow works to delete invisible paths?
There is a few invisible paths that we can use with the game right now from the Dev object menu (invisible pedestrian path, road paths, etc) but the issue is that once you place them, there is no way to remove them as nothing selects it.

Maybe as part of the Anarchy mode you could try to see if there is a way.

Thanks!

**Comment by yenyang** [comment]
I got that working with a Harmony Patch. It did cause a crash to desktop in my game if I didn't delete them in the right order, so it will be included in the next update but advised to save before hand and use with caution. I will close the issue when the next update occurs.

**Comment by yenyang** [comment]
Included in V1.1.0
