### ISSUE TITLE
Can't see invisible roads/paths while bulldoze tool is closed as of 1.2.2

### ISSUE THREAD

**Issue by Haneybd87** [yenyang/Anarchy-BepInEx#13]
Using 1.2.1 I could enable the target markers option with the bulldozer, and when I would exit the bulldozer tool I could still see invisible roads and paths to detail around them until I went back in and disabled target markers. Now when I exit the bulldozer tool I can no longer see the paths. It's just guesswork trying to place surfaces to make custom roads and paths.

**Comment by yenyang** [comment]
There shouldn't have been  any changes between 1.2.1 and 1.2.2 with how that works. Maybe between 1.2.0 and 1.2.1? 
But you can always toggle "show markers" with DevUI. Tab -> Gameplay -> Show Markers. 

I will take a look at how that's behaving though. I'm not sure if I like the way it's working right now. I wanted "Show Markers" to stay on if you were showing markers before you toggled the option to target markers. I also wanted it to turn off if you weren't showing markers before you toggled the option to target markers. 

We should probably talk to Alpha Gaming about adding a toggle for show markers to the area tool. 

In case you don't know this feature will be moving to a new mod called Better Bulldozer in the near future.

**Comment by Haneybd87** [comment]
Strange, it was definitely between 1.2.1 and 1.2.2, those are the only versions I've used so far. Thanks for the tip on the devUI option.

Edit: I left a post for Alpha Gaming suggesting a show markers toggle.

**Comment by yenyang** [comment]
I looked at and refined the show markers with v1.3.0 and made compatible with Better Bulldozer.
