### ISSUE TITLE
Trams and Trains continue to stall after most recent Anarchy update.

### ISSUE THREAD

**Issue by Lennonmapes** [yenyang/Anarchy-BepInEx#16]
The PreventOverride component is still an issue on my trams and trains, but the sims and cars seem to be fixed. I ran the game after the update with Anarchy installed then after noticing the issue persisted I disabled anarchy and reloaded. Trams and trains were still stuck so I rebuilt the areas of the track where they were getting stuck and redrew the lines. It doesn't matter what new track I build the trams will only get so far from the station before stalling permanently. Would love some help fixing this! Thank you for your hard work!

**Comment by yenyang** [comment]
https://github.com/yenyang/Anarchy-BepInEx/issues/14#issuecomment-1922865754

This person believes it’s a base game issue. 

I don’t believe it’s possible that the component is still causing the problems that you’re citing. The update removed it from any vehicles and cims, and you say you’d disabled the mod which also removes the component from everything. Yet you still had the issue.

**Comment by Lennonmapes** [comment]
> [#14 (comment)](https://github.com/yenyang/Anarchy-BepInEx/issues/14#issuecomment-1922865754)
> 
> This person believes it’s a base game issue.
> 
> I don’t believe it’s possible that the component is still causing the problems that you’re citing. The update removed it from any vehicles and cims, and you say you’d disabled the mod which also removes the component from everything. Yet you still had the issue.

That makes sense. Thanks for clarifying. Hopefully the devs can get to fixing this issue soon. Apologies for pointing the issue to the wrong source.

**Comment by yenyang** [comment]
It’s okay. Lots of people thought the issue Anarchy was causing was from
the game and not a mod. Luckily someone figured it out and told me.
