### ISSUE TITLE
Anarchy Mod  help 

### ISSUE THREAD

**Issue by renbuw** [yenyang/Anarchy-BepInEx#22]
[Error  : Unity Log] ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
Could not load type of field 'Anarchy.AnarchyMod:<Settings>k__BackingField' (2) due to: Could not resolve type with token 0100005f from typeref (expected class 'Game.Modding.ModSetting' in assembly 'Game, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null') assembly:Game, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null type:Game.Modding.ModSetting member:(null)
Could not resolve type with token 0100005f from typeref (expected class 'Game.Modding.ModSetting' in assembly 'Game, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null') assembly:Game, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null type:Game.Modding.ModSetting member:(null)
Stack trace:
System.Reflection.Assembly.GetTypes () (at <b89873cb176e44a995a4781c7487d410>:0)
Unity.Entities.TypeManager.InitializeAllComponentTypes () (at <44bbde2b9f584d7f9739ff08060d49d7>:0)
Unity.Entities.TypeManager.Initialize () (at <44bbde2b9f584d7f9739ff08060d49d7>:0)
Unity.Entities.AttachToEntityClonerInjection.Initialize () (at <2342a8de2d77430196f9dd8f6c3aee00>:0)
Unity.Entities.AttachToEntityClonerInjection..cctor () (at <2342a8de2d77430196f9dd8f6c3aee00>:0)
Rethrow as TypeInitializationException: The type initializer for 'Unity.Entities.AttachToEntityClonerInjection' threw an exception.
UnityEngine.DebugLogHandler:LogException(Exception, Object)
Colossal.Logging.CustomLogHandler:LogException(Exception, Object)
UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)

**Comment by renbuw** [comment]
[Error  : Unity Log] TypeLoadException: Could not load type of field 'Anarchy.AnarchyMod:<Settings>k__BackingField' (2) due to: Could not resolve type with token 0100005f from typeref (expected class 'Game.Modding.ModSetting' in assembly 'Game, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null') assembly:Game, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null type:Game.Modding.ModSetting member:(null)
Stack trace:
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.InputSystem.InputSystem:.cctor()

**Comment by yenyang** [comment]
I have only seen this error generated by people running old versions of the game that are incompatible with the mod. Update your game.
