### ISSUE TITLE
Crashing on startup

### ISSUE THREAD

**Issue by jayandare** [yenyang/Anarchy-BepInEx#5]
I'm getting an error that starts off with:
 TypeLoadException: Could not load type of field 'Anarchy.AnarchyMod:<Settings>k__BackingField'

I cannot figure out how to fix it

**Comment by yenyang** [comment]
I’ve never seen that before but is it possible you are using BepInEx 6?

**Comment by jayandare** [comment]
I don't think so. I attached an image. As soon as I can boot it up with only your mod I'll test again. I've been waiting for this mod!!!!!


![image](https://github.com/yenyang/Anarchy-BepInEx/assets/8580328/5de119a0-eeb9-4786-8e2e-4c2e6c375723)

**Comment by yenyang** [comment]
I don’t know what mod is causing that problem but you have a lot of duplicate DLL files. The image has nothing to do with my mod since my mod wouldn’t cause these problems.

**Comment by jayandare** [comment]
Here's the crash with just Anarchy and the unified library


Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 2 plugins to load
[Info   :   BepInEx] Loading [ 1.0.0.0]
[Error  : Unity Log] TypeLoadException: Could not load type of field 'Anarchy.AnarchyMod:<Settings>k__BackingField' (1) due to: Could not resolve type with token 01000050 from typeref (expected class 'Game.Modding.ModSetting' in assembly 'Game, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null') assembly:Game, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null type:Game.Modding.ModSetting member:(null)
Stack trace:
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset:OnEnable()

[Info   :   BepInEx] Loading [Unified Icon Library 1.0.6]
[Info   :   Console] Logs at C:/Users/jryan/AppData/LocalLow/Colossal Order/Cities Skylines II/Logs
[Message:   BepInEx] Chainloader startup complete
[Error  : Unity Log] ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
Could not load type of field 'Anarchy.AnarchyMod:<Settings>k__BackingField' (1) due to: Could not resolve type with token 01000050 from typeref (expected class 'Game.Modding.ModSetting' in assembly 'Game, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null') assembly:Game, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null type:Game.Modding.ModSetting member:(null)
Could not resolve type with token 01000050 from typeref (expected class 'Game.Modding.ModSetting' in assembly 'Game, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null') assembly:Game, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null type:Game.Modding.ModSetting member:(null)
Stack trace:
System.Reflection.Assembly.GetTypes () (at <b89873cb176e44a995a4781c7487d410>:0)
Unity.Entities.TypeManager.InitializeAllComponentTypes () (at <9823f950a18a49a1a4ada101a5698c63>:0)
Unity.Entities.TypeManager.Initialize () (at <9823f950a18a49a1a4ada101a5698c63>:0)
Unity.Entities.AttachToEntityClonerInjection.Initialize () (at <2342a8de2d77430196f9dd8f6c3aee00>:0)
Unity.Entities.AttachToEntityClonerInjection..cctor () (at <2342a8de2d77430196f9dd8f6c3aee00>:0)
Rethrow as TypeInitializationException: The type initializer for 'Unity.Entities.AttachToEntityClonerInjection' threw an exception.
UnityEngine.DebugLogHandler:LogException(Exception, Object)
Colossal.Logging.CustomLogHandler:LogException(Exception, Object)
UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)

[Info   : Unity Log] Game version: 1.0.14f1 (135.24916) [5275.25758]
[Info   : Unity Log] Type: Desktop
OS: Windows 11  (10.0.22000) 64bit
System memory: 15.869 GB
Graphics device: NVIDIA GeForce GTX 1050 Ti (Version: Direct3D 11.0 [level 11.1])
Graphics memory: 3.923 GB
Max texture size: 16384
Shader level: 50
3D textures: True
Shadows: True
Compute: True
CPU: Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
Core count: 4
Platform: WindowsPlayer
Screen resolution: 1920x1080x60
Window resolution: 1920x1080
DPI: 120
Rendering Threading Mode: LegacyJobified
CLR: 4.0.30319.42000
Scripting runtime: Mono 6.13.0 (Visual Studio built mono)
[Error  : Unity Log] [SceneFlow] [FATAL]  Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
Could not load type of field 'Anarchy.AnarchyMod:<Settings>k__BackingField' (1) due to: Could not resolve type with token 01000050 from typeref (expected class 'Game.Modding.ModSetting' in assembly 'Game, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null') assembly:Game, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null type:Game.Modding.ModSetting member:(null)
Could not resolve type with token 01000050 from typeref (expected class 'Game.Modding.ModSetting' in assembly 'Game, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null') assembly:Game, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null type:Game.Modding.ModSetting member:(null) System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
Could not load type of field 'Anarchy.AnarchyMod:<Settings>k__BackingField' (1) due to: Could not resolve type with token 01000050 from typeref (expected class 'Game.Modding.ModSetting' in assembly 'Game, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null') assembly:Game, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null type:Game.Modding.ModSetting member:(null)
Could not resolve type with token 01000050 from typeref (expected class 'Game.Modding.ModSetting' in assembly 'Game, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null') assembly:Game, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null type:Game.Modding.ModSetting member:(null)
  at (wrapper managed-to-native) System.Reflection.Assembly.GetTypes(System.Reflection.Assembly,bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <b89873cb176e44a995a4781c7487d410>:0 
  at Unity.Entities.TypeManager.InitializeAllComponentTypes () [0x00044] in <9823f950a18a49a1a4ada101a5698c63>:0 
  at Unity.Entities.TypeManager.Initialize () [0x001c0] in <9823f950a18a49a1a4ada101a5698c63>:0 
  at Unity.Entities.EntityManager.Initialize (Unity.Entities.World world) [0x00000] in <9823f950a18a49a1a4ada101a5698c63>:0 
  at Unity.Entities.WorldUnmanaged.Create (Unity.Entities.World world, Unity.Entities.WorldFlags flags, Unity.Collections.AllocatorManager+AllocatorHandle backingAllocatorHandle) [0x0006d] in <9823f950a18a49a1a4ada101a5698c63>:0 
  at Unity.Entities.World.Init (Unity.Entities.WorldFlags flags, Unity.Collections.AllocatorManager+AllocatorHandle backingAllocatorHandle) [0x00000] in <9823f950a18a49a1a4ada101a5698c63>:0 
  at Unity.Entities.World..ctor (System.String name, Unity.Entities.WorldFlags flags) [0x00044] in <9823f950a18a49a1a4ada101a5698c63>:0 
  at Game.SceneFlow.GameManager.CreateWorld () [0x00027] in <1f030b0a20a34c92a53f8d33297505a2>:0 
  at Game.SceneFlow.GameManager.Initialize () [0x001c0] in <1f030b0a20a34c92a53f8d33297505a2>:0 
System.TypeLoadException: Could not load type of field 'Anarchy.AnarchyMod:<Settings>k__BackingField' (1) due to: Could not resolve type with token 01000050 from typeref (expected class 'Game.Modding.ModSetting' in assembly 'Game, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null') assembly:Game, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null type:Game.Modding.ModSetting member:(null)
System.TypeLoadException: Could not resolve type with token 01000050 from typeref (expected class 'Game.Modding.ModSetting' in assembly 'Game, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null') assembly:Game, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null type:Game.Modding.ModSetting member:(null)
[Info   : Unity Log] Game terminated successfully

**Comment by yenyang** [comment]
You are several updates behind on the game and anarchy settings are not compatible with your version of the game. Please update your game if you want to use the mod.

**Comment by jayandare** [comment]
Awesome thank you so much for figuring it out.
