### ISSUE TITLE
Request: Add change log to Thunderstore page.

### ISSUE THREAD

**Issue by AgentX2006** [yenyang/Anarchy-BepInEx#7]
I see an update but there is nothing to tell me what is new or has changed.

**Comment by yenyang** [comment]
I’m sorry I don’t have a formal change log yet. I post about updates on the Cities : Skylines Modding Discord. Here’s the post:

**Anarchy Updated to v1.2.0**
[Available on Thunderstore](https://thunderstore.io/c/cities-skylines-ii/p/yenyang/Anarchy/)

As previously announced at https://discordapp.com/channels/1024242828114673724/1185958132179009549/1191489868514218043 .

Anarchy now has an opt-in option to allow placing multiple copies of unique buildings using the normal UI menu with or without Anarchy enabled. The effects of these buildings stack!

Comment Section at https://discordapp.com/channels/1024242828114673724/1185958132179009549 .


I’ll work on getting a change log for Thunderstore for the next update.

**Comment by yenyang** [comment]
Added this and it will be updated on-going and included with Thunderstore upload.

https://github.com/yenyang/Anarchy-BepInEx/blob/master/CHANGELOG.md

**Comment by yenyang** [comment]
Added with V1.2.1
